FROM golang:1.8-alpine
ADD . /go/src/rest-api
RUN apk add --update git
RUN go get -d github.com/gorilla/mux
RUN go install rest-api 

FROM alpine:latest
COPY --from=0 /go/bin/rest-api .
ENV PORT 8080
CMD ["./rest-api"]
